steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
artifacts:
    npmPackages:
    - repository: 'https://us-west1-npm.pkg.dev/pc-api-8109002212129309923-974/NodeOAuth2'
        packagePath: '.'
timeout: '1600s'
