steps:
  - name: 'gcr.io/cloud-builders/npm'
    name: 'node'
    entrypoint: 'npm'
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud run deploy --source']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1600s'
